/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './header.component.ngfactory';
import * as i2 from './header.component';
import * as i3 from '@angular/router';
import * as i4 from './errors/error.component.ngfactory';
import * as i5 from './errors/error.component';
import * as i6 from './errors/error.service';
import * as i7 from './app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),9,'div',[['class',
      'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(2,0,(null as any),
          (null as any),1,'app-header',([] as any[]),(null as any),(null as any),(null as any),
          i1.View_HeaderComponent_0,i1.RenderType_HeaderComponent)),i0.ɵdid(3,49152,
          (null as any),0,i2.HeaderComponent,([] as any[]),(null as any),(null as any)),
      (_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(5,0,(null as any),
          (null as any),0,'hr',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n    '])),
      (_l()(),i0.ɵeld(7,16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(8,212992,(null as any),0,i3.RouterOutlet,[i3.ChildrenOutletContexts,
          i0.ViewContainerRef,i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],
          (null as any),(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n'])),(_l()(),
          i0.ɵted(-1,(null as any),['\n'])),(_l()(),i0.ɵeld(11,0,(null as any),(null as any),
          1,'app-error',([] as any[]),(null as any),(null as any),(null as any),i4.View_ErrorComponent_0,
          i4.RenderType_ErrorComponent)),i0.ɵdid(12,114688,(null as any),0,i5.ErrorComponent,
          [i6.ErrorService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,8,0);
    _ck(_v,12,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(1,49152,(null as any),0,i7.AppComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i7.AppComponent> = i0.ɵccf('my-app',
    i7.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWVoZGkgSWNoa2FycmFuZS9EZXNrdG9wL0NvdXJzIEluZm9ybWF0aXF1ZS9Db3VycyBhbmd1bGFyX25vZGUtanMvTWF4IEhlbHAgZmlsZS8wOCBPcHRpbWl6YXRpb25zL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9NZWhkaSBJY2hrYXJyYW5lL0Rlc2t0b3AvQ291cnMgSW5mb3JtYXRpcXVlL0NvdXJzIGFuZ3VsYXJfbm9kZS1qcy9NYXggSGVscCBmaWxlLzA4IE9wdGltaXphdGlvbnMvYXNzZXRzL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvTWVoZGkgSWNoa2FycmFuZS9EZXNrdG9wL0NvdXJzIEluZm9ybWF0aXF1ZS9Db3VycyBhbmd1bGFyX25vZGUtanMvTWF4IEhlbHAgZmlsZS8wOCBPcHRpbWl6YXRpb25zL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvTWVoZGkgSWNoa2FycmFuZS9EZXNrdG9wL0NvdXJzIEluZm9ybWF0aXF1ZS9Db3VycyBhbmd1bGFyX25vZGUtanMvTWF4IEhlbHAgZmlsZS8wOCBPcHRpbWl6YXRpb25zL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gICAgPGFwcC1oZWFkZXI+PC9hcHAtaGVhZGVyPlxuICAgIDxocj5cbiAgICA8cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XG48L2Rpdj5cbjxhcHAtZXJyb3I+PC9hcHAtZXJyb3I+IiwiPG15LWFwcD48L215LWFwcD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQXVCLDhDQUNuQjtVQUFBO2lFQUFBLFVBQUE7VUFBQTtNQUF5Qiw4Q0FDekI7VUFBQTtVQUFBLDhCQUFJO01BQ0o7VUFBQTthQUFBOzBEQUFBO1VBQUEsNkJBQStCLDBDQUM3QjtpQkFBQSwyQkFDTjtVQUFBO3NDQUFBLFVBQUE7VUFBQTtJQUZJO0lBRUo7Ozs7b0JDTEE7TUFBQTthQUFBO1VBQUE7OzsifQ==
