/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './message-input.component.ngfactory';
import * as i2 from './message-input.component';
import * as i3 from './message.service';
import * as i4 from './message-list.component.ngfactory';
import * as i5 from './message-list.component';
import * as i6 from './messages.component';
const styles_MessagesComponent:any[] = ([] as any[]);
export const RenderType_MessagesComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_MessagesComponent,data:{}});
export function View_MessagesComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),4,'div',[['class','row']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
      ['\n            '])),(_l()(),i0.ɵeld(3,0,(null as any),(null as any),1,'app-message-input',
      ([] as any[]),(null as any),(null as any),(null as any),i1.View_MessageInputComponent_0,
      i1.RenderType_MessageInputComponent)),i0.ɵdid(4,114688,(null as any),0,i2.MessageInputComponent,
      [i3.MessageService],(null as any),(null as any)),(_l()(),i0.ɵted(-1,(null as any),
      ['\n        '])),(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(7,
      0,(null as any),(null as any),0,'hr',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
      ['\n        '])),(_l()(),i0.ɵeld(9,0,(null as any),(null as any),4,'div',[['class',
      'row']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n            '])),(_l()(),i0.ɵeld(11,0,(null as any),
          (null as any),1,'app-message-list',([] as any[]),(null as any),(null as any),
          (null as any),i4.View_MessageListComponent_0,i4.RenderType_MessageListComponent)),
      i0.ɵdid(12,114688,(null as any),0,i5.MessageListComponent,[i3.MessageService],
          (null as any),(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n        '])),
      (_l()(),i0.ɵted(-1,(null as any),['\n    ']))],(_ck,_v) => {
    _ck(_v,4,0);
    _ck(_v,12,0);
  },(null as any));
}
export function View_MessagesComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app-messages',
      ([] as any[]),(null as any),(null as any),(null as any),View_MessagesComponent_0,
      RenderType_MessagesComponent)),i0.ɵdid(1,49152,(null as any),0,i6.MessagesComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const MessagesComponentNgFactory:i0.ComponentFactory<i6.MessagesComponent> = i0.ɵccf('app-messages',
    i6.MessagesComponent,View_MessagesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWVoZGkgSWNoa2FycmFuZS9EZXNrdG9wL0NvdXJzIEluZm9ybWF0aXF1ZS9Db3VycyBhbmd1bGFyX25vZGUtanMvTWF4IEhlbHAgZmlsZS8wOCBPcHRpbWl6YXRpb25zL2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZXMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL01laGRpIEljaGthcnJhbmUvRGVza3RvcC9Db3VycyBJbmZvcm1hdGlxdWUvQ291cnMgYW5ndWxhcl9ub2RlLWpzL01heCBIZWxwIGZpbGUvMDggT3B0aW1pemF0aW9ucy9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL01laGRpIEljaGthcnJhbmUvRGVza3RvcC9Db3VycyBJbmZvcm1hdGlxdWUvQ291cnMgYW5ndWxhcl9ub2RlLWpzL01heCBIZWxwIGZpbGUvMDggT3B0aW1pemF0aW9ucy9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC50cy5NZXNzYWdlc0NvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvTWVoZGkgSWNoa2FycmFuZS9EZXNrdG9wL0NvdXJzIEluZm9ybWF0aXF1ZS9Db3VycyBhbmd1bGFyX25vZGUtanMvTWF4IEhlbHAgZmlsZS8wOCBPcHRpbWl6YXRpb25zL2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZXMuY29tcG9uZW50LnRzLk1lc3NhZ2VzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgICAgICAgIDxhcHAtbWVzc2FnZS1pbnB1dD48L2FwcC1tZXNzYWdlLWlucHV0PlxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGhyPlxuICAgICAgICA8ZGl2IGNsYXNzPVwicm93XCI+XG4gICAgICAgICAgICA8YXBwLW1lc3NhZ2UtbGlzdD48L2FwcC1tZXNzYWdlLWxpc3Q+XG4gICAgICAgIDwvZGl2PlxuICAgICIsIjxhcHAtbWVzc2FnZXM+PC9hcHAtbWVzc2FnZXM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQSxrREFDUTtNQUFBO01BQUEsNENBQWlCO01BQUEscUJBQ2I7TUFBQTt5Q0FBQSxVQUFBO01BQUEsaURBQXVDO01BQUEsaUJBQ3JDLGtEQUNOO01BQUE7TUFBQSw0Q0FBSTtNQUFBLGlCQUNKO01BQUE7TUFBaUIsc0RBQ2I7VUFBQTtVQUFBO2FBQUE7VUFBQSw2QkFBcUM7TUFDbkM7SUFMRjtJQUlBOzs7O29CQ05aO01BQUE7a0NBQUEsVUFBQTtNQUFBOzs7In0=
